version: "3.9"

services: 
  mongo:
    image: mongo:5.0.4
    restart: unless-stopped
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - ${MONGO_DIR_DATA}:/data/db

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  apiapp:
    container_name: apiapp
    image: fofware/firulais_backend:v0.48
    restart: unless-stopped
#    ports: 
#      - 4000:4400
    environment:
#      MONGODB_USER: root
#      MONGODB_PASSWORD: example
      MONGODB_URI: mongodb://mongo/gestion

  websrv:
    container_name: websrv
    image: fofware/mydockersrvweb:0.0.16
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_CONF_D}:/etc/nginx/conf.d
      - ${NGINX_DEFAULT}:/usr/share/nginx/html
      - ${NGINX_WEBROOTS}:/webroots
      - ${LETSENCRYPT}:/etc/letsencrypt
#      - ${SCRIPTS}:/scripts
      - ${IMAGES_DIR_DATA}:/webroots/firulais.net.ar/assets/images

#  mphumberto:
#    container_name: mphumberto
#    image: webdevops/php-nginx:8.0-alpaine