# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:5.0.4
    restart: unless-stopped
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
      - 27084:27017

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: fabian
      ME_CONFIG_BASICAUTH_PASSWORD: Tamara01
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
